### ISSUE TITLE
helics_goss_bridge crashes when opening switch from Viz

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/GOSS-GridAPPS-D#1533]
The helics_goss_bridge is crashing in latest develop when trying to open a switch from Viz, running simulation on IEEE 123 model.
```
2021-06-23 14:58:36,908 Thread-39 INFO [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1624460316908|helics_goss_bridge.py|1093527122|RUNNING|system|INFO
Sending the following message to the simulator. {
    "1093527122": {
        "external_event_handler": {},
        "swt_sw2": {

2021-06-23 14:58:36,948 Thread-39 ERROR [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1624460316948|helics_goss_bridge.py|1093527122|ERROR|system|ERROR
An error occured while trying to translate the update message received
Traceback (most recent call last):
  File "/gridappsd/services/helicsgossbridge/service/helics_goss_bridge.py", line 915, in _publish_to_helics_bus
    helics.helicsEndpointSendMessage(helics_input_endpoint, helics_msg)
  File "/usr/local/lib/python3.7/site-packages/helics/helics.py", line 3199, in helicsEndpointSendMessage
    return _helics.helicsEndpointSendMessage(endpoint, message)
TypeError: in method 'helicsEndpointSendMessage', argument 2 of type 'helics_message *'


2021-06-23 14:58:36,952 Thread-39 ERROR [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1624460316952|helics_goss_bridge.py|1093527122|ERROR|system|ERROR
Error in run simulation Traceback (most recent call last):
  File "/gridappsd/services/helicsgossbridge/service/helics_goss_bridge.py", line 915, in _publish_to_helics_bus
    helics.helicsEndpointSendMessage(helics_input_endpoint, helics_msg)
  File "/usr/local/lib/python3.7/site-packages/helics/helics.py", line 3199, in helicsEndpointSendMessage
    return _helics.helicsEndpointSendMessage(endpoint, message)
TypeError: in method 'helicsEndpointSendMessage', argument 2 of type 'helics_message *'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gridappsd/services/helicsgossbridge/service/helics_goss_bridge.py", line 567, in run_simulation
    self._publish_to_helics_bus(self._simulation_command_queue.get(), self._command_filter)
  File "/gridappsd/services/helicsgossbridge/service/helics_goss_bridge.py", line 928, in _publish_to_helics_bus
    raise RuntimeError(err_msg)
RuntimeError: An error occured while trying to translate the update message received
Traceback (most recent call last):
  File "/gridappsd/services/helicsgossbridge/service/helics_goss_bridge.py", line 915, in _publish_to_helics_bus
    helics.helicsEndpointSendMessage(helics_input_endpoint, helics_msg)
  File "/usr/local/lib/python3.7/site-packages/helics/helics.py", line 3199, in helicsEndpointSendMessage
    return _helics.helicsEndpointSendMessage(endpoint, message)
TypeError: in method 'helicsEndpointSendMessage', argument 2 of type 'helics_message *'



2021-06-23 14:58:36,955 Thread-39 ERROR [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1624460316909|gov.pnnl.goss.gridappsd.simulation.SimulationProcess$1|Simulator-1093527122|ERROR|system|ERROR
ERROR    [2021-06-23 14:57:05 UTC] : received SIGABRT; exiting now
```

**Comment by AAndersn** [comment]
No longer relevant. This was caused by a breaking change in 2021.05.0 release.
