### ISSUE TITLE
Store alarms and faults in Proven

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#860]

**Comment by ericstephan** [comment]
@poorva1209 , do you have guidance for me on the data you need uploading?

**Comment by poorva1209** [comment]
Alarms service output: 
[{"equipment_mrid": "_EAC7564D-2126-4138-8525-26B63DB6FDEE", "value": 0, "created_by": "system", "equipment_name": "cap1"}, {"equipment_mrid": "_8A595A9C-8E80-48F8-AB45-FAD8E487D6FE", "value": 0, "created_by": "system", "equipment_name": "cap2"}]

I will add one more key "phases":"ABC" to each object in this output but I don't think Proven would care about that. 

In order to test this:
1. Remove line number 211 from ProvenTimeseriesDataManager:  if(serviceId.equals("gridappsd-alarms"))
2. Build your local gridappsd container
3. Start simualtion with sample app (any model)

**Comment by ericstephan** [comment]
Is this just a measurement? (in other words does this go into the same measurement table as the simulation data?) @poorva1209

**Comment by poorva1209** [comment]
This should go into a separate measurement - alarms.  Not simulation output.

**Comment by ericstephan** [comment]
@poorva1209 The timestamp is missing from the Alarms service output.  Does this format work for you?

{"timestamp":1248159974, "alarms":[{"equipment_mrid": "_EAC7564D-2126-4138-8525-26B63DB6FDEE", "value": 0, "created_by": "system", "equipment_name": "cap1"}, {"equipment_mrid": "_8A595A9C-8E80-48F8-AB45-FAD8E487D6FE", "value": 0, "created_by": "system", "equipment_name": "cap2"}]}

**Comment by ericstephan** [comment]
@poorva1209 Or perhaps instead of a new tag “alarms” just use what we used for simulation output “measurements” ?


{"timestamp":1248159974, "measurements":[{"equipment_mrid": "_EAC7564D-2126-4138-8525-26B63DB6FDEE", "value": 0, "created_by": "system", "equipment_name": "cap1"}, {"equipment_mrid": "_8A595A9C-8E80-48F8-AB45-FAD8E487D6FE", "value": 0, "created_by": "system", "equipment_name": "cap2"}]}


From: Eric Stephan <Eric.Stephan@pnnl.gov>
Date: Monday, November 4, 2019 at 15:08
To: GRIDAPPSD/GOSS-GridAPPS-D <reply@reply.github.com>, GRIDAPPSD/GOSS-GridAPPS-D <GOSS-GridAPPS-D@noreply.github.com>
Cc: "ericphb@gmail.com" <ericphb@gmail.com>, Assign <assign@noreply.github.com>
Subject: Re: [GRIDAPPSD/GOSS-GridAPPS-D] Store alarms and faults in Proven (#860)

@poorva1209 The timestamp is missing from the Alarms service output.  Does this format work for you?

{"timestamp":1248159974, "alarms":[{"equipment_mrid": "_EAC7564D-2126-4138-8525-26B63DB6FDEE", "value": 0, "created_by": "system", "equipment_name": "cap1"}, {"equipment_mrid": "_8A595A9C-8E80-48F8-AB45-FAD8E487D6FE", "value": 0, "created_by": "system", "equipment_name": "cap2"}]}

**Comment by poorva1209** [comment]
I have to update the alarms service to include a timestamp in it. 
I don't think it matters to the gridappsd API where it stores as long as all the current API for storing and querying simulation output and input still works.

**Comment by ericstephan** [comment]
If it doesn't matter I can just use current time.  Influx can handle this no problem

**Comment by ericstephan** [comment]
@poorva1209<mailto:notifications@github.com> What is the new format, is it the last one I suggested?

Eric

**Comment by ericstephan** [comment]
@poorva1209 I got to thinking about the alarm output format.   Shouldn't it be in the same dictionary format that we are moving toward for simulation output?

{"timestamp":1248159974, "message":{"_EAC7564D-2126-4138-8525-26B63DB6FDEE":{"equipment_mrid": "_EAC7564D-2126-4138-8525-26B63DB6FDEE", "value": 0, "created_by": "system", "equipment_name": "cap1"}, "_8A595A9C-8E80-48F8-AB45-FAD8E487D6FE" : {"equipment_mrid": "_8A595A9C-8E80-48F8-AB45-FAD8E487D6FE", "value": 0, "created_by": "system", "equipment_name": "cap2"}}

**Comment by ericstephan** [comment]
Poorva,

Have you ever seen this error?  I built the gridappsd container and attempting to run run-gridappsd.sh

Eric

org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Jakarta Commons Logging API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Log4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Avalon Logger API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling JULI Logger API support.
Updating configuration properties
CREATING LOG DATA MGR MYSQL
java.lang.IllegalArgumentException: Username may not be null
                at org.apache.http.util.Args.notNull(Args.java:54)
                at org.apache.http.auth.UsernamePasswordCredentials.<init>(UsernamePasswordCredentials.java:78)
                at gov.pnnl.goss.gridappsd.data.LogDataManagerMySQL.start(LogDataManagerMySQL.java:107)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.felix.dm.runtime.InvocationUtil.invokeMethod(InvocationUtil.java:101)
                at org.apache.felix.dm.runtime.InvocationUtil.invokeCallbackMethod(InvocationUtil.java:47)
                at org.apache.felix.dm.runtime.ServiceLifecycleHandler.invokeMethod(ServiceLifecycleHandler.java:353)
                at org.apache.felix.dm.runtime.ServiceLifecycleHandler.start(ServiceLifecycleHandler.java:280)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.felix.dm.impl.InvocationUtil.invokeMethod(InvocationUtil.java:131)
                at org.apache.felix.dm.impl.InvocationUtil.invokeCallbackMethod(InvocationUtil.java:86)
                at org.apache.felix.dm.impl.ComponentImpl.invokeCallbackMethod(ComponentImpl.java:540)
                at org.apache.felix.dm.impl.ComponentImpl.invoke(ComponentImpl.java:1493)
                at org.apache.felix.dm.impl.ComponentImpl.invokeStart(ComponentImpl.java:1027)
                at org.apache.felix.dm.impl.ComponentImpl.performTransition(ComponentImpl.java:993)
                at org.apache.felix.dm.impl.ComponentImpl.handleChange(ComponentImpl.java:926)
                at org.apache.felix.dm.impl.ComponentImpl.handleAdded(ComponentImpl.java:1077)
                at org.apache.felix.dm.impl.ComponentImpl.lambda$4(ComponentImpl.java:466)
                at org.apache.felix.dm.impl.SerialExecutor.runTask(SerialExecutor.java:138)
                at org.apache.felix.dm.impl.SerialExecutor.runTasks(SerialExecutor.java:120)
                at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:86)
                at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:105)
                at org.apache.felix.dm.impl.ComponentImpl.handleEvent(ComponentImpl.java:462)
                at org.apache.felix.dm.impl.ServiceDependencyImpl.addedService(ServiceDependencyImpl.java:256)
                at org.apache.felix.dm.tracker.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1278)
                at org.apache.felix.dm.tracker.ServiceTracker$Tracked$2.execute(ServiceTracker.java:1394)
                at org.apache.felix.dm.tracker.ServiceTracker$Tracked$1.run(ServiceTracker.java:1191)
                at org.apache.felix.dm.impl.SerialExecutor.runTask(SerialExecutor.java:138)
                at org.apache.felix.dm.impl.SerialExecutor.runTasks(SerialExecutor.java:120)
                at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:86)
                at org.apache.felix.dm.tracker.ServiceTracker$Tracked.serviceChangedHideAspects(ServiceTracker.java:1197)
                at org.apache.felix.dm.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1052)
                at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:987)
                at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
                at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
                at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4536)
                at org.apache.felix.framework.Felix.registerService(Felix.java:3518)
                at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
                at org.apache.felix.dm.impl.ComponentImpl.registerService(ComponentImpl.java:1300)
                at org.apache.felix.dm.impl.ComponentImpl.performTransition(ComponentImpl.java:995)
                at org.apache.felix.dm.impl.ComponentImpl.handleChange(ComponentImpl.java:926)
                at org.apache.felix.dm.impl.ComponentImpl.handleAdded(ComponentImpl.java:1077)
                at org.apache.felix.dm.impl.ComponentImpl.lambda$4(ComponentImpl.java:466)
                at org.apache.felix.dm.impl.SerialExecutor.runTask(SerialExecutor.java:138)
                at org.apache.felix.dm.impl.SerialExecutor.runTasks(SerialExecutor.java:120)
                at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:86)
                at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:105)
                at org.apache.felix.dm.impl.ComponentImpl.handleEvent(ComponentImpl.java:462)
                at org.apache.felix.dm.impl.ConfigurationDependencyImpl.updated(ConfigurationDependencyImpl.java:280)
                at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:148)
                at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:81)
                at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1448)
                at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1404)
                at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:103)
                at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalArgumentException: Username may not be null
                at org.apache.http.util.Args.notNull(Args.java:54)
                at org.apache.http.auth.UsernamePasswordCredentials.<init>(UsernamePasswordCredentials.java:78)
                at gov.pnnl.goss.gridappsd.log.LogManagerImpl.start(LogManagerImpl.java:113)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.felix.dm.runtime.InvocationUtil.invokeMethod(InvocationUtil.java:101)
                at org.apache.felix.dm.runtime.InvocationUtil.invokeCallbackMethod(InvocationUtil.java:47)
                at org.apache.felix.dm.runtime.ServiceLifecycleHandler.invokeMethod(ServiceLifecycleHandler.java:353)
                at org.apache.felix.dm.runtime.ServiceLifecycleHandler.start(ServiceLifecycleHandler.java:280)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.felix.dm.impl.InvocationUtil.invokeMethod(InvocationUtil.java:131)
                at org.apache.felix.dm.impl.InvocationUtil.invokeCallbackMethod(InvocationUtil.java:86)
                at org.apache.felix.dm.impl.ComponentImpl.invokeCallbackMethod(ComponentImpl.java:540)
                at org.apache.felix.dm.impl.ComponentImpl.invoke(ComponentImpl.java:1493)
                at org.apache.felix.dm.impl.ComponentImpl.invokeStart(ComponentImpl.java:1027)
                at org.apache.felix.dm.impl.ComponentImpl.performTransition(ComponentImpl.java:993)
                at org.apache.felix.dm.impl.ComponentImpl.handleChange(ComponentImpl.java:926)
                at org.apache.felix.dm.impl.ComponentImpl.handleAdded(ComponentImpl.java:1077)
                at org.apache.felix.dm.impl.ComponentImpl.lambda$4(ComponentImpl.java:466)
                at org.apache.felix.dm.impl.SerialExecutor.runTask(SerialExecutor.java:138)
                at org.apache.felix.dm.impl.SerialExecutor.runTasks(SerialExecutor.java:120)
                at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:86)
                at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:105)
                at org.apache.felix.dm.impl.ComponentImpl.handleEvent(ComponentImpl.java:462)
                at org.apache.felix.dm.impl.ServiceDependencyImpl.addedService(ServiceDependencyImpl.java:256)
                at org.apache.felix.dm.tracker.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1278)
                at org.apache.felix.dm.tracker.ServiceTracker$Tracked$2.execute(ServiceTracker.java:1394)
                at org.apache.felix.dm.tracker.ServiceTracker$Tracked$1.run(ServiceTracker.java:1191)
                at org.apache.felix.dm.impl.SerialExecutor.runTask(SerialExecutor.java:138)
                at org.apache.felix.dm.impl.SerialExecutor.runTasks(SerialExecutor.java:120)
                at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:86)
                at org.apache.felix.dm.tracker.ServiceTracker$Tracked.serviceChangedHideAspects(ServiceTracker.java:1197)
                at org.apache.felix.dm.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1052)
                at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:987)
                at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
                at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
                at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4536)
                at org.apache.felix.framework.Felix.registerService(Felix.java:3518)
                at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
                at org.apache.felix.dm.impl.ComponentImpl.registerService(ComponentImpl.java:1300)
                at org.apache.felix.dm.impl.ComponentImpl.performTransition(ComponentImpl.java:995)
                at org.apache.felix.dm.impl.ComponentImpl.handleChange(ComponentImpl.java:926)
                at org.apache.felix.dm.impl.ComponentImpl.handleAdded(ComponentImpl.java:1077)
                at org.apache.felix.dm.impl.ComponentImpl.lambda$4(ComponentImpl.java:466)
                at org.apache.felix.dm.impl.SerialExecutor.runTask(SerialExecutor.java:138)
                at org.apache.felix.dm.impl.SerialExecutor.runTasks(SerialExecutor.java:120)
                at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:86)
                at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:105)
                at org.apache.felix.dm.impl.ComponentImpl.handleEvent(ComponentImpl.java:462)
                at org.apache.felix.dm.impl.ServiceDependencyImpl.addedService(ServiceDependencyImpl.java:256)
                at org.apache.felix.dm.tracker.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1278)
                at org.apache.felix.dm.tracker.ServiceTracker$Tracked$2.execute(ServiceTracker.java:1394)
                at org.apache.felix.dm.tracker.ServiceTracker$Tracked$1.run(ServiceTracker.java:1191)
                at org.apache.felix.dm.impl.SerialExecutor.runTask(SerialExecutor.java:138)
                at org.apache.felix.dm.impl.SerialExecutor.runTasks(SerialExecutor.java:120)
                at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:86)
                at org.apache.felix.dm.tracker.ServiceTracker$Tracked.serviceChangedHideAspects(ServiceTracker.java:1197)
                at org.apache.felix.dm.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1052)
                at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:987)
                at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
                at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
                at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4536)
                at org.apache.felix.framework.Felix.registerService(Felix.java:3518)
                at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
                at org.apache.felix.dm.impl.ComponentImpl.registerService(ComponentImpl.java:1300)
                at org.apache.felix.dm.impl.ComponentImpl.performTransition(ComponentImpl.java:995)
                at org.apache.felix.dm.impl.ComponentImpl.handleChange(ComponentImpl.java:926)
                at org.apache.felix.dm.impl.ComponentImpl.handleAdded(ComponentImpl.java:1077)
                at org.apache.felix.dm.impl.ComponentImpl.lambda$4(ComponentImpl.java:466)
                at org.apache.felix.dm.impl.SerialExecutor.runTask(SerialExecutor.java:138)
                at org.apache.felix.dm.impl.SerialExecutor.runTasks(SerialExecutor.java:120)
                at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:86)
                at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:105)
                at org.apache.felix.dm.impl.ComponentImpl.handleEvent(ComponentImpl.java:462)
                at org.apache.felix.dm.impl.ConfigurationDependencyImpl.updated(ConfigurationDependencyImpl.java:280)
                at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:148)
                at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:81)
                at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1448)
                at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1404)
                at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:103)
                at java.lang.Thread.run(Thread.java:748)

**Comment by poorva1209** [comment]
Please make sure that your Viz and gridappsd containers are up to date. We added authentication to know who is the user that is sending the message this week.

**Comment by ericstephan** [comment]
That worked.

When I run the 13 node simulation I’m not seeing alarm messages.  Do I need to run a large simulation?

Eric

**Comment by poorva1209** [comment]
Did you run with sample_app ?

**Comment by ericstephan** [comment]
At first I didn’t, I am now running with the sample_app.  I do see alarms on the tab.  I did a docker build by running the build-docker.sh script.  I didn’t do a gradle build.

**Comment by poorva1209** [comment]
So now you are seeing alarms in influxdb ?

**Comment by ericstephan** [comment]
Sorry for the "false alarm" 😉.  No just in the gridappsd-app.  I am looking through the messages and report to you what I am finding.

Eric

________________________________

**Comment by poorva1209** [comment]
Did you follow these steps :+1: 

In order to test this:

1. Remove line number 211 from ProvenTimeseriesDataManager: if(serviceId.equals("gridappsd-alarms"))
2. Build your local gridappsd container
3. Start simualtion with sample app (any model)

**Comment by ericstephan** [comment]
Yes I followed these steps.  This is the code I blocked:

       public void storeServiceOutput(String simulationId, String serviceId, String instanceId) throws Exception {
                //TODO: Remove this once alarms are stored in Proven
                //if(!serviceId.equals("gridappsd-alarms"))
                    subscribeAndStoreDataFromTopic("/topic/"+GridAppsDConstants.topic_simulation+"."+serviceId+"."+simulationId+".output", serviceId, instanceId);
        }

I am receiving this notice as the simulation is running.


{
    "source": "fncs_goss_bridge.py",
    "processId": "1374610640",
    "timestamp": 1573171115000,
    "processStatus": "RUNNING",
    "logMessage": "All measurements for object xf_reg1a are missing from the simulator output.",
    "logLevel": "WARN",
    "storeToDb": true
}

**Comment by poorva1209** [comment]
@ericstephan I followed following steps and don't see any alarms in the influxdb: 

1. Create containers with develop tag: ./run.sh -t develop
2. In goss-gridapps-d repository folder:
  2.1 Remove line number 211 from ProvenTimeseriesDataManager: 
            if(serviceId.equals("gridappsd-alarms"))
  2.2 Execute ./build-docker.sh script. This will replace jar file in existing running gridappsd container. 
3.  Go inside gridappsd container and start simualtion with sample app (any model)

Expected result :
1. Alarms tab on Viz should show alarms 
2. InfluxDb container should have alarms measurement. 

Let me know if I need to use some other tag for proven and influx to test this. If not, we need to figure out why this is not working.

**Comment by poorva1209** [comment]
@ericstephan I made some changes in goss-gridapps-d and ran a simulation with sample_app that generates alarms. I can see alarms in the influx db with the changes.
But I think we need to add service instance id and simulation id to the data otherwise we won't know what data corresponds to what simulation. We can talk about it tomorrow when you are back. 

![image](https://user-images.githubusercontent.com/6538501/87471909-f3f65580-c5d3-11ea-9292-706376efb31f.png)

**Comment by poorva1209** [comment]
FYI, this is the output message from alarms service: 

[{"equipment_mrid": "_D6C44FF1-BC60-49D3-9438-DFAD1AED0A28", "value": "Close", "created_by": "system", "equipment_name": "c83", "phases": "ABC"}, {"equipment_mrid": "_CABBC3A1-66F5-4B9C-ACB9-476E2389D119", "value": "Close", "created_by": "system", "equipment_name": "c88a", "phases": "A"}, {"equipment_mrid": "_3DE55D2D-34D3-487E-9D6E-3A4DB1E38E47", "value": "Close", "created_by": "system", "equipment_name": "c90b", "phases": "B"}, {"equipment_mrid": "_939CA567-AA3D-4972-AABC-1D0AAF4859FE", "value": "Close", "created_by": "system", "equipment_name": "c92c", "phases": "C"}]
