### ISSUE TITLE
gridappsd-sensor-simulator service throws error (branch temcdrm)

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#927]
### Description of Issue
temcdrm branch for gridappsd-sensor-simulator throws an error. Looks like it is trying to add a float ans an mrid value: 90856.7493315 and _9d4a3436-c5b1-4d87-a406-84c0fce22ac6

Exception in thread StompReceiverThread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/gridappsd/.local/lib/python2.7/site-packages/stomp/transport.py", line 349, in __receiver_loop
    self.process_frame(f, frame)
  File "/home/gridappsd/.local/lib/python2.7/site-packages/stomp/transport.py", line 192, in process_frame
    self.notify(frame_type, f.headers, f.body)
  File "/home/gridappsd/.local/lib/python2.7/site-packages/stomp/transport.py", line 248, in notify
    rtn = notify_func(headers, body)
  File "/usr/local/lib/python2.7/dist-packages/gridappsd/goss.py", line 184, in on_message
    self._callback(header, message)
  File "sensor_simulator.py", line 171, in on_simulation_message
    new_value = self.get_new_value(t, value)
  File "sensor_simulator.py", line 128, in get_new_value
    self.add_sample (t, value)
  File "sensor_simulator.py", line 91, in add_sample
    self._average = self._average + val
TypeError: unsupported operand type(s) for +: 'float' and 'unicode'

I printed out self._average and val and I got 90856.7493315 _9d4a3436-c5b1-4d87-a406-84c0fce22ac6 respectively.

Note that simulation output format may have changed since this service was last written so it may need some editing.

**Comment by poorva1209** [comment]
Issue moved to [GRIDAPPSD/gridappsd-sensor-simulator #5](https://github.com/GRIDAPPSD/gridappsd-sensor-simulator/issues/5) via [**ZenHub**](https://www.zenhub.com/)
