### ISSUE TITLE
CIM/blazegraph update broke IEEE 13 bus circuit

### ISSUE THREAD

**Issue by blthayer** [GRIDAPPSD/GOSS-GridAPPS-D#929]
@poorva1209 @temcdrm @tdtalbot - assigning Poorva for now so she can redirect as needed.

When I fired up the platform this morning (05/04), I noticed a new container was pulled for blazegraph. Upon trying to run a simulation for the IEEE 13 bus system, we get the following output (error at the bottom). Note this was functioning for me yesterday with no errors.

```
Thread-42 INFO [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1559661461906|gov.pnnl.goss.gridappsd.process.ProcessNewSimulationRequest|1410616013|RUNNING|system|INFO
Parsed config {"power_system_config":{"SubGeographicalRegion_name":"_1CD7D2EE-3C91-3248-5662-A4
Thread-42 INFO [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1559661461910|ProcessNewSimulationRequest|1410616013|RUNNING|system|INFO
Creating simulation and power grid model files for simulation Id 1410616013

Thread-42 INFO [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1559661461918|gov.pnnl.goss.gridappsd.configuration.GLDAllConfigurationHandler|1410616013|RUNNING|system|INFO
Generating all GridLAB-D configuration files using parameters: {load_scaling_factor=1.0, i
{load_scaling_factor=1.0, i_fraction=1.0, p_fraction=0.0, model_id=_49AD8E07-3BF9-A4E2-CB8F-C3722F837B62, simulation_id=1410616013, z_fraction=0.0, simulation_broker_host=127.0.0.1, simulation_name=ieee13nodeckt, simulation_duration=5, simulation_start_time=1248152400, solver_method=NR, schedule_name=ieeezipload, randomize_zipload_fractions=false, simulation_broker_port=61137, directory=/tmp/gridappsd_tmp/1410616013, use_houses=true}
{load_scaling_factor=1.0, i_fraction=1.0, p_fraction=0.0, model_id=_49AD8E07-3BF9-A4E2-CB8F-C3722F837B62, simulation_id=1410616013, z_fraction=0.0, simulation_broker_host=127.0.0.1, simulation_name=ieee13nodeckt, simulation_duration=5, simulation_start_time=1248152400, solver_method=NR, schedule_name=ieeezipload, randomize_zipload_fractions=false, simulation_broker_port=61137, directory=/tmp/gridappsd_tmp/1410616013, use_houses=true}
{load_scaling_factor=1.0, i_fraction=1.0, p_fraction=0.0, model_id=_49AD8E07-3BF9-A4E2-CB8F-C3722F837B62, simulation_id=1410616013, z_fraction=0.0, simulation_broker_host=127.0.0.1, simulation_name=ieee13nodeckt, simulation_duration=5, simulation_start_time=1248152400, solver_method=NR, schedule_name=ieeezipload, randomize_zipload_fractions=false, simulation_broker_port=61137, directory=/tmp/gridappsd_tmp/1410616013, use_houses=true}
{load_scaling_factor=1.0, i_fraction=1.0, p_fraction=0.0, model_id=_49AD8E07-3BF9-A4E2-CB8F-C3722F837B62, simulation_id=1410616013, z_fraction=0.0, simulation_broker_host=127.0.0.1, simulation_name=ieee13nodeckt, simulation_duration=5, simulation_start_time=1248152400, solver_method=NR, schedule_name=ieeezipload, randomize_zipload_fractions=false, simulation_broker_port=61137, directory=/tmp/gridappsd_tmp/1410616013, use_houses=true}
{load_scaling_factor=1.0, i_fraction=1.0, p_fraction=0.0, model_id=_49AD8E07-3BF9-A4E2-CB8F-C3722F837B62, simulation_id=1410616013, z_fraction=0.0, simulation_broker_host=127.0.0.1, simulation_name=ieee13nodeckt, simulation_duration=5, simulation_start_time=1248152400, solver_method=NR, schedule_name=ieeezipload, randomize_zipload_fractions=false, simulation_broker_port=61137, directory=/tmp/gridappsd_tmp/1410616013, use_houses=true}
{load_scaling_factor=1.0, i_fraction=1.0, p_fraction=0.0, model_id=_49AD8E07-3BF9-A4E2-CB8F-C3722F837B62, simulation_id=1410616013, z_fraction=0.0, simulation_broker_host=127.0.0.1, simulation_name=ieee13nodeckt, simulation_duration=5, simulation_start_time=1248152400, solver_method=NR, schedule_name=ieeezipload, randomize_zipload_fractions=false, simulation_broker_port=61137, directory=/tmp/gridappsd_tmp/1410616013, use_houses=true}
Thread-42 INFO [org.glassfish.jersey.internal.ServiceFinder] - Running in an OSGi environment
Thread-42 INFO [org.glassfish.jersey.process.internal.ExecutorProviders] - Selected ExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
Thread-42 INFO [org.glassfish.jersey.process.internal.ExecutorProviders] - Selected ScheduledExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientBackgroundSchedulerProvider] to be used for injection of scheduler qualified by [org.glassfish.jersey.client.ClientBackgroundScheduler] annotation.
Thread-42 INFO [org.glassfish.jersey.client.internal.HttpUrlConnector] - Restricted headers are not enabled using [sun.net.http.allowRestrictedHeaders] system property (setting only takes effect on connections created after the property has been set/changed).
200
LOOKING FOR CONVERTER PROVEN_WEATHER:GRIDLABD_WEATHER  IN   {PROVEN_WEATHER:GRIDLABD_WEATHER=gov.pnnl.goss.gridappsd.data.conversion.ProvenWeatherToGridlabdWeatherConverter@17d28a44}
Thread-42 INFO [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1559661467188|gov.pnnl.goss.gridappsd.configuration.GLDAllConfigurationHandler|1410616013|RUNNING|system|INFO
Generating startup file for GridLAB-D configuration using parameters: {load_scaling_factor
Thread-42 INFO [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1559661467218|gov.pnnl.goss.gridappsd.configuration.GLDAllConfigurationHandler|1410616013|RUNNING|system|INFO
Finished generating startup file for GridLAB-D configuration.

Thread-42 INFO [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1559661467220|gov.pnnl.goss.gridappsd.configuration.GLDSimulationOutputConfigurationHandler|1410616013|RUNNING|system|INFO
Generating simulation output configuration file using parameters: {dictionary
Thread-42 ERROR [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1559661467234|gov.pnnl.goss.gridappsd.configuration.GLDSimulationOutputConfigurationHandler|1410616013|ERROR|system|ERROR
Error while generating simulation output: CimMeasurementsToGldPubs::parseMeasurement: The value of ConductingEquipment_type is not a recognized object type.
Valid types are ACLineSegment, LinearShuntCompesator, RatioTapChanger, LoadBreakSwitch, EnergyConsumer, PowerElectronicsConnection, and PowerTransformer.
ConductingEquipment_type = Recloser_rec1_Voltage.

com.google.gson.JsonParseException: CimMeasurementsToGldPubs::parseMeasurement: The value of ConductingEquipment_type is not a recognized object type.
Valid types are ACLineSegment, LinearShuntCompesator, RatioTapChanger, LoadBreakSwitch, EnergyConsumer, PowerElectronicsConnection, and PowerTransformer.
ConductingEquipment_type = Recloser_rec1_Voltage.
	at gov.pnnl.goss.gridappsd.configuration.GLDSimulationOutputConfigurationHandler.parseMeasurement(GLDSimulationOutputConfigurationHandler.java:397)
	at gov.pnnl.goss.gridappsd.configuration.GLDSimulationOutputConfigurationHandler.CreateGldPubs(GLDSimulationOutputConfigurationHandler.java:229)
	at gov.pnnl.goss.gridappsd.configuration.GLDSimulationOutputConfigurationHandler.generateConfig(GLDSimulationOutputConfigurationHandler.java:194)
	at gov.pnnl.goss.gridappsd.configuration.GLDAllConfigurationHandler.generateConfig(GLDAllConfigurationHandler.java:295)
	at gov.pnnl.goss.gridappsd.configuration.ConfigurationManagerImpl.generateConfiguration(ConfigurationManagerImpl.java:171)
	at gov.pnnl.goss.gridappsd.process.ProcessNewSimulationRequest.process(ProcessNewSimulationRequest.java:222)
	at gov.pnnl.goss.gridappsd.process.ProcessEvent.onMessage(ProcessEvent.java:165)
	at pnnl.goss.core.client.GossClient$1.run(GossClient.java:321)
	at java.lang.Thread.run(Thread.java:748)
Thread-42 ERROR [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1559661467237|gov.pnnl.goss.gridappsd.process.ProcessNewSimulationRequest|1410616013|ERROR|system|ERROR
Process Initialization error: CimMeasurementsToGldPubs::parseMeasurement: The value of ConductingEquipment_type is not a recognized object type.
Valid types are ACLineSegment, LinearShuntCompesator, RatioTapChanger, LoadBreakSwitch, EnergyConsumer, PowerElectronicsConnection, and PowerTransformer.
ConductingEquipment_type = Recloser_rec1_Voltage.

```

**Comment by afisher1** [comment]
Somehow this model has a breaker, fuse, and recloser object in it. I need to modify the bridge and the configuration handler to handle these new object types.

**Comment by blthayer** [comment]
@afisher1 - just to reiterate (and possibly avoid chasing down issues that aren't truly the root cause): I was able to successfully run this model yesterday.

Thanks for diving in!

**Comment by blthayer** [comment]
@afisher1 - as far as I can tell, this is now working.
